#! /usr/local/bin/bash

# Ensure the user has passed a search term
if [[ $# -eq 0 ]]; then
    echo -e "\nPlease provide a search term...\n"
    exit 1
fi

# Query the package database for the provided string and echo a numbered list of results
echo -e "\nQuerying package database for '$1'\n"
pkg_info -Q $1 | grep -n $1

# Calculate the total number of packages containing the search string
TOTAL=$(pkg_info -Q $1 | wc -l | awk '{print$1}')

# If no results are returned exit
if [[ $TOTAL -lt 1 ]]; then
  echo -e "No packages containing the string '$1' were found!\n\nExiting...\n"
  exit 1
fi

# Echo the total number of packages found containing the search string
echo -e "\nThere were $TOTAL packages found\n"

# Prompt the user for a package to install
while :
do
  read -r -p "Which would you like to install? " ANSWER
    case $ANSWER in
      [0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])
          if [[ $ANSWER -gt $TOTAL || $ANSWER == '0' ]]; then
            echo -e "\nPlease enter a number within the result range...\n"
          else
            SELECTED=$(pkg_info -Q $1 | grep -n $1 | grep "^$ANSWER" | cut -d ':' -f2 | awk '{print$1}')
            echo -e "\nInstalling $SELECTED\n"
            sudo pkg_add $SELECTED;
            echo -e "\n$SELECTED installed successfully!"
            break
          fi
          ;;
       *)
          echo -e "\nPlease enter the number of the package you'd like to install....\n"
    esac
done
